# NUMPY

In [2]:
import numpy as np


In [3]:
a = np.array([2,3,4])

In [4]:
a


array([2, 3, 4])

In [5]:
a.dtype

dtype('int32')

In [6]:
b = np.array([1.2, 3.5, 5.1])

In [7]:
b

array([1.2, 3.5, 5.1])

In [8]:
b.dtype

dtype('float64')

In [18]:
b
    

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [7]:
b = np.array([(1.5,2,3), (4,5,6)])


In [8]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [9]:
c = np.array( [ [1,2], [3,4] ], dtype=complex )

In [10]:
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [11]:
np.zeros( (3,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.ones( (2,3,4), dtype=np.int16 )

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [16]:
np.empty( (2,3) )

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [13]:
np.ones( (2,3,4, 5), dtype=np.int16 )

array([[[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]],


       [[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]]], dtype=int16)

In [46]:
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [19]:
np.arange( 0, 2, 0.3 )

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [20]:
from numpy import pi

In [47]:
np.linspace( 0, 2, 12 )

array([0.        , 0.18181818, 0.36363636, 0.54545455, 0.72727273,
       0.90909091, 1.09090909, 1.27272727, 1.45454545, 1.63636364,
       1.81818182, 2.        ])

In [22]:
x = np.linspace( 0, 2*pi, 100 )

In [23]:
x

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [14]:
a = np.arange(6)

In [25]:
a

array([0, 1, 2, 3, 4, 5])

In [26]:
print(a)

[0 1 2 3 4 5]


In [27]:
b = np.arange(12).reshape(4,3)

In [15]:
print(b)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [16]:
c = np.arange(24).reshape(2,3,4)

In [30]:
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [31]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [32]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [33]:
a = np.array( [20,30,40,50] )

In [34]:
a


array([20, 30, 40, 50])

In [35]:
b = np.arange( 4 )

In [36]:
b

array([0, 1, 2, 3])

In [37]:
c = a-b

In [38]:
c

array([20, 29, 38, 47])

In [39]:
b**2

array([0, 1, 4, 9], dtype=int32)

In [40]:
B = np.arange(3)


In [41]:
b

array([0, 1, 2, 3])

In [42]:
B

array([0, 1, 2])

In [1]:
import pandas as pd


In [2]:
import numpy as np
