In [11]:
import numpy as np
my_array = np.array([[1,2,3],[4,5,6],[7,8,9]],dtype =np.int64)
print(my_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
# Create an empty array
earray = np.empty((2,3))
earray.itemsize

8

In [16]:
# Create a full array
fullarray = np.full((2,2),9)
print(fullarray)
print(fullarray.size)



[[9 9]
 [9 9]]
4


In [19]:
evenlyspaced = np.linspace(0,9,4)
evenlyspaced

array([0., 3., 6., 9.])

In [27]:
boolarray = np.full((4,4),False, dtype = bool)
boolarray

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [34]:
onearray = np.ones((4,4),dtype = bool)
onearray

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [44]:
arr = [0,1,2,3,4,5,6,7,8,9]
arr

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [50]:
arr1 = np.array([0,1,2,3,4,5,6,7,8,9])
print(arr1)
oddnum = arr[arr%2 ==1]
print(oddnum)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[0 1 2 3 4 5 6 7 8 9]


In [72]:
a = np.arange(8).reshape(2,-1)
print(a)
b = np.repeat(2,10).reshape(2,-1)
b

[[0 1 2 3]
 [4 5 6 7]]


array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])